Update playwright-scheduled.yml

diff --git a/.github/workflows/playwright-scheduled.yml b/.github/workflows/playwright-scheduled.yml
--- a/.github/workflows/playwright-scheduled.yml
+++ b/.github/workflows/playwright-scheduled.yml
@@ -18,88 +18,66 @@ jobs:
 
     - name: Install dependencies
       run: npm install
-      
+
     - name: Install Playwright Browsers
       run: npx playwright install
 
-    - name: Install Json summary report
-      run: npm install playwright-slack-report -D
-
     - name: Run Playwright tests
-      run: npx playwright test test-environment/test-cases/team-courses/team-courses.test.js --reporter=json --output=./test-results/summary.json
-
-    - name: Upload Playwright report
-      uses: actions/upload-artifact@v4
-      with:
-        name: playwright-report
-        path: ./test-results
+      run: npx playwright test test-environment/test-cases/team-courses/team-courses.test.js --reporter=json --output=./test-results
 
     - name: List test-results directory
-      run: ls -R ./test-results
-        
-    - name: Read Summary Report to Get Test Results
-      if: always()
+      run: ls -R ./test-results || echo "Directory ./test-results does not exist."
+
+    - name: Parse Test Results
+      id: parse_results
       run: |
-         STATUS=$(cat ./summary.json | jq -r '.status')
-         echo "STATUS=$STATUS" >> $GITHUB_ENV 
-         PASSED=$(cat ./summary.json | jq -r '.passed[]' | tr '\n' ' ')
-         echo "PASSED=$PASSED" >> $GITHUB_ENV 
-         TIMEOUT=$(cat ./summary.json | jq -r '.timedOut[]' | tr '\n' ' ' | sed 's/ /--->TIMEOUT /g')
-         FAILURES=$(cat ./summary.json | jq -r '.failed[]' | tr '\n' ' ')
-         FAILURES+=$TIMEOUT
-         echo "FAILURES=$FAILURES" >> $GITHUB_ENV
+        if [ -f ./test-results/results.json ]; then
+          PASSED=$(jq -r '.tests | map(select(.status == "passed")) | length' ./test-results/results.json)
+          FAILED=$(jq -r '.tests | map(select(.status == "failed")) | length' ./test-results/results.json)
+          echo "PASSED=$PASSED" >> $GITHUB_ENV
+          echo "FAILED=$FAILED" >> $GITHUB_ENV
+        else
+          echo "No results.json file found!"
+          echo "PASSED=0" >> $GITHUB_ENV
+          echo "FAILED=0" >> $GITHUB_ENV
+        fi
+
     - name: Send Slack Notification
       if: always()
       uses: 8398a7/action-slack@v3
       with:
-          status: custom
-          fields: repo,eventName,workflow,job,took
-          custom_payload: |
-            {
-              attachments: [{
-                color: '${{ job.status }}' === 'success' ? 'good' : 'danger',
-                title: `Playwright Demo Automation Results :test_tube:`,
-                fields: [{
-                  title: 'Site Under Test',
-                  value: '${{ env.APP_URL }}',
-                  short: true
-                },
-                {
-                  title: 'Triggered By',
-                  value: [{'origin': 'pull_request', 'new': 'Pull Request'}, {'origin': 'schedule', 'new': 'Schedule'}, {'origin': 'repository_dispatch', 'new': 'Deploy'}, {'origin': 'workflow_dispatch', 'new': 'GitHub Actions'}].find(item => item.origin === `${process.env.AS_EVENT_NAME}`).new || `${process.env.AS_EVENT_NAME}`,
-                  short: true
-                },
-                {
-                  title: 'Repo',
-                  value: `${process.env.AS_REPO}`,
-                  short: true
-                },
-                {
-                  title: 'Execution Time',
-                  value: `${process.env.AS_TOOK}`,
-                  short: true
-                },
-                {
-                  title: 'Workflow',
-                  value: `${process.env.AS_WORKFLOW}`,
-                  short: true
-                },
-                {
-                  title: 'Total Tests',
-                  value: (`${{ env.FAILURES }}`.match(/.spec.ts/g) || []).length + (`${{ env.PASSED }}`.match(/.spec.ts/g) || []).length,
-                  short: true
-                },
-                {
-                  title: 'Pull Request',
-                  value: `${{ env.PULL_REQUEST_URL }}`,
-                  short: false
-                },
-                {
-                  title: 'Failures',
-                  value: `${{ env.FAILURES }}` === '' ? 'No failures' : `${{ env.FAILURES }}`.match(/.spec.ts/g).length > 10 ? `Too many failures to print. Please go to GitHub to see full list of failures` : '```${{ env.FAILURES }}```'.replace(/ /g, '\n'),
-                  short: false
-                }]
-              }]
-            }  
+        status: ${{ job.status }}
+        fields: repo,eventName,workflow,job,took
+        custom_payload: |
+          {
+            "attachments": [
+              {
+                "color": "${{ job.status == 'success' ? 'good' : 'danger' }}",
+                "title": "Playwright Test Results :test_tube:",
+                "fields": [
+                  {
+                    "title": "Tests Passed",
+                    "value": "${{ env.PASSED }}",
+                    "short": true
+                  },
+                  {
+                    "title": "Tests Failed",
+                    "value": "${{ env.FAILED }}",
+                    "short": true
+                  },
+                  {
+                    "title": "Workflow",
+                    "value": "${{ github.workflow }}",
+                    "short": true
+                  },
+                  {
+                    "title": "Job",
+                    "value": "${{ job.name }}",
+                    "short": true
+                  }
+                ]
+              }
+            ]
+          }
       env:
-          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
+        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
